### ISSUE TITLE
admin-ui has not compiled since #130: LocalUserAdmin is not exported from @plenipo/ui

### ISSUE THREAD

**Issue by abrahamFerga** [abrahamFerga/Plenipo#135]
`frontend/admin-ui` fails to build, and has since #130. Every pull request opened since then fails
the **Frontend lint, test, build & E2E** job, whatever it changed.

```text
admin-ui build: src/admin/LocalUsersPanel.tsx(3,52): error TS2305:
  Module '"@plenipo/ui"' has no exported member 'LocalUserAdmin'.
[ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL] @plenipo/admin-ui@0.1.0-alpha build: `tsc -b && vite build`
```

## Cause

`LocalUsersPanel.tsx` types the `Auth:Mode=Local` user table with `LocalUserAdmin`, which is declared
in `@plenipo/client` (`frontend/plenipo-client/src/api.ts:962`) and reaches `plenipo-ui` through
`lib/api.ts`'s `export * from "@plenipo/client"`.

But `frontend/plenipo-ui/src/index.ts` re-exports **named symbols**, not `export *`. A type that is
reachable through the API surface — `api.admin.localUsers()` returns `LocalUserAdmin[]` — is
therefore not reachable through the package until it is named in the index. `AuthConfig`, its
neighbour on the same auth surface, is named there; this one was missed.

## Why it landed unseen

`ci.yml` is:

```yaml
on:
  pull_request:
  push:
    branches-ignore:
      - main
```

so `main` never runs CI. The break was introduced on a branch whose own CI presumably predated the
admin-ui consumer, merged, and then began failing every *subsequent* PR — where it reads as "the
frontend is broken" rather than "main is broken".

Worth considering separately: a repo whose default branch is never built cannot tell you it is
broken. That is what turned a one-line omission into a blocker for every open PR.

## Reproduction

```bash
cd frontend && pnpm install && pnpm build:all
```

**Comment by abrahamFerga** [comment]
Correcting the "Why it landed unseen" section before someone builds the fix it implies.

This issue attributes the break to `ci.yml` being `push: branches-ignore: [main]`. That trigger is
real, but it is not why #130 landed broken — and the fix it suggests (add `main` to the push trigger)
would not have prevented this.

**#130 ran no CI at all.** Head `768c30e7c6a1b96be5d9cebd62e3762ffa0fbd0f` returns
`total_count: 0` check-runs. `ci.yml` has a bare `pull_request:` trigger, so a PR branch normally
does get CI — #136's own head has 19 checks.

The pattern is temporal, not configurational:

| PR | branch | merged | checks on head |
|---|---|---|---|
| #124 | `fix/*` | 17:42Z | 19 |
| #122 | `fix/*` | 17:54Z | 22 |
| **#126** | `fix/*` | **20:03Z** | **1** |
| **#130** | `claude/*` | **20:03Z** | **0** |
| #134 | `claude/*` | (open, 23:54Z) | 22 |

#130 and #126 were merged manually at 20:03Z, inside the GitHub Actions major outage that ran from
~16:32Z to ~23:30Z and created no runs anywhere in this repo. So: **a human merged #130 while the
gate physically could not run.** `checks_exist` in `merge-gate.mjs` is the gate that refuses exactly
that, and a manual `gh pr merge` bypasses the script entirely.

It is also not a `claude/*` branch problem — #134 is on a `claude/*` branch and has 22 checks.

**What this issue correctly identifies** is the *second* hole: because `main` never runs CI, the
break stayed invisible afterwards, surfacing only as "every open PR's frontend job is red" rather
than "main is broken". That is worth fixing on its own merits — it cost a day of misattribution —
but it should be filed as *detection latency on main*, not as the cause.

The cause, if it is to be addressed at all, is that a human merging by hand has no equivalent of
`checks_exist`. Branch protection requiring the CI checks would be the mechanism; that changes the
merge bar, so it is a human's call.

— `/plenipo:steward` tick, 2026-08-07T00:3xZ. Evidence L1: check-run counts read from the API per
head SHA; merge timestamps from `gh pr view`.

**Comment by abrahamFerga** [comment]
Fixed on `main` — closing with the evidence, since the PR that carried the fix did not link this issue.

The `LocalUserAdmin` re-export landed in 2b1df18 ("Vendor the fixed merge gate, and let the merger close linked issues", #143). That PR's body says `Closes #142` and never named this issue, so it stayed open after its defect was gone.

**What is on `main` now** (ea8794a):

- `frontend/plenipo-ui/src/index.ts:148` — `export type { AuthConfig, LocalUserAdmin } from "./lib/api";`
- `eng/verify-frontend-packaging.sh` — a `const localUser: LocalUserAdmin` in the packed-tarball consumer, so the export is guarded from outside the monorepo rather than relying on `admin-ui` happening to import it.

**L1 proof, run on `main` at ea8794a just now:**

```text
$ cd frontend && pnpm build:all
plenipo-client build: Done
plenipo-ui build: OK built in 1.86s
plenipo-ui build: Done
admin-ui build: OK built in 1.71s
admin-ui build: Done
EXIT=0
```

`admin-ui` compiles. The **Frontend lint, test, build & E2E** job is no longer failing for this reason on every unrelated PR.

**Not fixed by this, and deliberately left open elsewhere:** the reason this landed unseen in the first place — `ci.yml` is `push: branches-ignore: [main]`, so `main` never runs CI and a break arriving on the default branch is only ever reported against other people's PRs. That is a `.github/` change and is not an unattended agent's to make.

PR #136 proposed the same fix independently and is superseded; closing it separately.
